### ISSUE TITLE
SConstruct broken?

### ISSUE THREAD

**Issue by luizesramos** [jimstevens2001/marss.hybridsim#1]
While compiling marss.hybridsim, I'm getting a compiler error when scons enters the 'ptlsim/core' directory (after it it successfully builds the 'build' and 'cache' directories). I was wondering if the master version is stable or if is still under development. Thanks!

In file included from ptlsim/build/core/atom-core/atomcore.cpp:11:0:
ptlsim/core/atom-core/atomcore.h: In instantiation of ‘int atom::TranslationLookasideBuffer<tlbid, size>::flush_virt(Waddr, W64) [with int tlbid = 0; int size = 32; Waddr = long long unsigned int; W64 = long long unsigned int]’:
ptlsim/build/core/atom-core/atomcore.cpp:3250:40:   required from here
ptlsim/core/atom-core/atomcore.h:462:56: error: ‘invalidate’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
ptlsim/core/atom-core/atomcore.h:462:56: note: declarations in dependent base ‘FullyAssociativeTagsNbitOneHot<32, 40, 0>’ are not found by unqualified lookup
ptlsim/core/atom-core/atomcore.h:462:56: note: use ‘this->invalidate’ instead
ptlsim/core/atom-core/atomcore.h: In instantiation of ‘int atom::TranslationLookasideBuffer<tlbid, size>::flush_virt(Waddr, W64) [with int tlbid = 1; int size = 32; Waddr = long long unsigned int; W64 = long long unsigned int]’:
ptlsim/build/core/atom-core/atomcore.cpp:3251:40:   required from here
ptlsim/core/atom-core/atomcore.h:462:56: error: ‘invalidate’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
ptlsim/core/atom-core/atomcore.h:462:56: note: declarations in dependent base ‘FullyAssociativeTagsNbitOneHot<32, 40, 0>’ are not found by unqualified lookup
ptlsim/core/atom-core/atomcore.h:462:56: note: use ‘this->invalidate’ instead
g++ -o ptlsim/build/core/branchpred.o -c -g3 -O3 -march=native -mtune=native -DDISABLE_ASSERT -DDISABLE_LOGGING -fno-trapping-math -fstack-protector -fno-exceptions -fno-rtti -funroll-loops -fstrict-aliasing -DNUM_SIM_CORES=1 -DSINGLE_CORE_MEM_CONFIG -DENABLE_L3_CACHE -DNEED_CPU_H -D__STDC_FORMAT_MACROS -DMARSS_QEMU -D__x86_64__ -DGITBRANCH=features -DGITCOMMIT=dcd3dc -DGITDATE='Thu May 24 00:46:22 2012' -Wall -Wendif-labels -Wwrite-strings -Wno-redundant-decls -Iptlsim/core/ooo-core -Iptlsim/core/atom-core -fexceptions -DMONGO_HAVE_STDINT -Iqemu -Iqemu/target-i386 -Iqemu/fpu -Iqemu/x86_64-softmmu -Iptlsim/cache -Iptlsim/core -Iptlsim/lib -Iptlsim/sim -Iptlsim/stats -Iptlsim/tools -Iptlsim/x86 ptlsim/build/core/branchpred.cpp
scons: **\* [ptlsim/build/core/atom-core/atomcore_atom.o] Error 1
scons: building terminated because of errors.
make: **\* [all] Error 2

**Comment by jimstevens2001** [comment]
Are you referring to the marss.hybridsim branch? We don't have a branch called "master" for this project. 

To answer your question... No, I haven't had any problems with the SConstruct on our setups (Ubuntu 10.04 and 12.04). This code works well on our local setup, but we have not attempted to do any sort of testing outside of our configuration whatsoever, so there may be an issue we don't know about.

Can you send me the exact commands you are using to check out and compile it?

**Comment by luizesramos** [comment]
Jim, thanks for replying. Yes, I'm referring to the marss.hybridsim branch. I'm trying to run MARSS with HybridSim (and DRAMSim2 + NVDIMMSim), so I downloaded into a same directory (let's say /home/user/) and tried to build them, except for marss.hybridsim. I'm using Linux Mint (Olivia) 64-bit,s which is also Debian-based. To give you an idea, marss.dramsim compiles without warnings on this machine. What I did was:

git clone git://github.com/dramninjasUMD/DRAMSim2.git
git clone git://github.com/jimstevens2001/NVDIMMSim
git clone git://github.com/jimstevens2001/HybridSim
git clone git://github.com/jimstevens2001/marss.hybridsim

cd /home/user/DRAMSim2
make libdramsim.so # compiled successfully

cd /home/user/NVDIMMSim/src
make libnvdsim.so # compiled successfully

cd /home/user/HybridSim
make libhybridsim.so # compiled successfully

cd /home/user/marss.hybridsim

Below is a list of what I tried, but they all fail to compile.

scons -Q # as in the README file (generates the output of my previous post)

scons dramsim=/home/user/marssx86/DRAMSim2/ # as in the marss.dramsim branch

scons hybridsim=/home/user/marssx86/HybridSim/

scons dramsim=/home/user/marssx86/DRAMSim2/ hybridsim=/home/user/marssx86/HybridSim/

scons dramsim=/home/user/marssx86/HybridSim/

I hope it's just a matter of incorrect scons arguments. 
Looking forward to hear from you.  
Thanks for your time and help!

**Comment by jimstevens2001** [comment]
I believe I've found your problem...

https://github.com/dramninjasUMD/marss.dramsim/commit/cdb795333f28b105fad5158f59544e148ca2e88f

That commit is not in marss.hybridsim since I haven't merged anything from marss mainline in for a long time. We have had similar compiler problems in the past when we went from Ubuntu 10.04 to 12.04.

For now, just apply that change locally and you should have no problem running on the 13.04/Mint 15 toolchain.

I am planning on merging my stuff with the latest version of marss in the near future and that should correct this problem in the repo.

Let me know if that works for you.

**Comment by luizesramos** [comment]
Fantastic! This little patch alone allowed it to compile until the end on Mint 15, using g++ (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3. In fact, there were very few warnings in the successful compilation.
-            return invalidate(tagof(virtaddr, threadid));
-            return this->invalidate(tagof(virtaddr, threadid));

Thanks for the heads up on the difference between marss.dramsim and marss.hybridsim. I'll keep that in mind.
Thanks again!
