### ISSUE TITLE
Compiling marss.hybridsim, HybridSim.h: No such file or directory

### ISSUE THREAD

**Issue by saeidbarati157** [jimstevens2001/marss.hybridsim#2]
Hi Jim. 
While compiling marss.hybridsim, I ran into this problem.
ptlsim/cache/memoryController.h:37:23: fatal error: HybridSim.h: No such file or directory
compilation terminated.

It seems that linking the hybridsim.so doesn't working properly. 
I'm not sure how to tell marss to use that shared library.

I followed the steps that is mentioned in https://github.com/jimstevens2001/marss.hybridsim/issues/1  and none of those Scons combinations didn't work for me too. (All .so have compiled successfully)

I would be thankful if you can help through this.
--Saeid

**Comment by jimstevens2001** [comment]
This does not appear to be a linking issue. It appears to be a path issue. The scons script assumes that the HybridSim folder is located at ../HybridSim relative to the marss.hybridsim folder. If you do that, then the path passed to g++ and the linker should work correctly.

For reference, this is the command I use to compile marss.hybridsim...

scons c=4 -j16 dramsim=`pwd`/../HybridSim

Set the c parameter to however many cores you need.

**Comment by saeidbarati157** [comment]
I temporarily solved the problem by copying .h files from Hybridsim folder into marss.hybridsim folder. And everything seems works correct.

Thank you kindly
